# Generated by Django 2.1.7 on 2019-03-21 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dining',
            options={'verbose_name_plural': 'Dining'},
        ),
        migrations.AlterModelOptions(
            name='freemeal',
            options={'verbose_name_plural': 'Free Meal'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['priority'], 'verbose_name_plural': 'Menu'},
        ),
    ]
