# Generated by Django 2.1.7 on 2019-03-21 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetails',
            options={'verbose_name_plural': 'User Details'},
        ),
        migrations.AlterModelOptions(
            name='userpoints',
            options={'verbose_name_plural': 'User Points'},
        ),
    ]
